version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: go_server
    ports:
      - '8080:8080'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_client
    ports:
      - '3000:80'
    depends_on:
      - server
